In [37]:
import numpy as np
from numpy import linalg as LA
from scipy.sparse import diags

In [130]:
#jacobi & gauss-seidel method
def linear_iterative_methods(A, b, x, eps, max_iter, method="gauss_seidel", log=True):
    D=np.diag(np.diag(A))
    T=A-D
    err=0
    k=1
    if log:
        print("Init state")
        print("A =\n",A)
        print("b =",b)
        print("x =",x)
        print("max_iter =",max_iter,", method =",method,"\n")
        print("iteration\tx_vector\terr")
    while(k<=max_iter):
        x_prev = np.copy(x)
        for i in range(len(A)):
            if method=="jacobian":
                x[i] = ((np.sum(-1*T[i]*x_prev))+b[i]) / A[i][i]
            elif method=="gauss_seidel":
                x[i] = ((np.sum(-1*T[i]*x))+b[i]) / A[i][i]
        err=np.linalg.norm(x-x_prev)/np.linalg.norm(x, np.inf)
        if log:
            print(str(k)+"\t", str(x)+"\t", str(err)+"\n")
        if(err<eps):
            break
        k+=1
    return x, k

#tridiagonal algorithm
def tridiagonal_algo(A, d, x):
    #matrix separation
    b = np.copy(np.diag(A))
    a = np.concatenate(([0], np.diagonal(A,-1))) #lower
    c = np.concatenate((np.diagonal(A,1), [0])) #upper
    n=len(A)
    #thomas algorithm
    #forward sweep:
    for i in range(1, n):
        w = a[i]/float(b[i-1])
        b[i] = b[i] - (w*c[i-1])
        d[i] = d[i] - (w*d[i-1])
    #back-substitution:
    x[n-1] = d[n-1]/b[n-1]
    for i in range(n-2, -1, -1):
        x[i] = (d[i] - c[i]*x[i+1])/b[i]
    return x

In [126]:
x=np.zeros((4))
A=np.array([[10,-1,2,0],[-1,11,-1,3],[2,-1,10,-1],[0,3,-1,8]])
b=np.array([6, 25, -11, 15])
x, k=linear_iterative_methods(A, b, x, 0.001, 20, method = 'jacobian', log=False)

In [127]:
#tridiagonal system
x=np.zeros((3))
A=np.array([[3,-1,0],
            [-1,3,-1],
            [0,-1,3]])
b=np.array([-1,7,7])
x, k=linear_iterative_methods(A, b, x, 0.001, 20, method = 'jacobian', log=False)

In [131]:
#testing tridiagonal algo
#init matrices
#matrix from https://www.slideshare.net/ParidhiMadurar/thomas-algorithm
x=np.zeros((3))
A=(np.array([[3,-1,0],
            [-1,3,-1],
            [0,-1,3]])).astype('float64')
d=(np.array([-1,7,7])).astype('float64')

print(tridiagonal_algo(A, d, x))


[0.95238095 3.85714286 3.61904762]


In [153]:
#Problem 2 :
A = (np.array([[3,1,1],
              [1,5,1],
              [1,1,3]])).astype('float64')
n = 20 
x = np.zeros((n,3))
x[0] = np.array([0,1,0])
print(x)
for k in range(n-1):
    res = np.matmul(A, x[k])
    print(res)
    x[k+1] = res/LA.norm(res)
print(x)

[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 5. 1.]
[1.73205081 5.19615242 1.73205081]
[2.11057941 5.12569286 2.11057941]
[2.28747855 5.03245282 2.28747855]
[2.37062925 4.97067423 2.37062925]
[2.41062801 4.93604782 2.41062801]
[2.43020478 4.91781597 2.43020478]
[2.43988419 4.90847291 2.43988419]
[2.44469626 4.90374494 2.44469626]
[2.44709533 4.90136689 2.44709533]
[2.44829312 4.90017436 2.44829312]
[2.44889158 4.89957721 2.44889158]
[2.4491907  4.89927842 2.4491907 ]
[2.44934023 4.89912897 2.44934023]
[2.44941499 4.89905423 2.44941499]
[2.44945237 4.89901686 2.44945237]
[2.44947105 4.89899817 2.44947105]
[2.4494804  4.89898883 2.4494804 ]
[2.44948507 4.89898416 2.44948507]
[[0.         1.         0.        ]
 [0.19245009 0.96225045 0.19245009]
 [0.30151134 0.90453403 0.30151134]
 [0.35583 

In [6]:
w, v = LA.eig(np.array([[3,1,1],[1,5,1],[1,1,3]]))
print(w)
print(v)

[6. 2. 3.]
[[-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [-8.16496581e-01  9.72565920e-16 -5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]
